#!/usr/bin/env bash
#
# CHPMS — Interactive Setup Wizard (macOS / Linux)
# Run from inside the unzipped delivery folder:
#   chmod +x setup.sh
#   ./setup.sh
#

set -e

cd "$(dirname "$0")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}  CHPMS — Coconut Husk Processing Management System         ${NC}"
echo -e "${CYAN}  Setup Wizard v1.0                                         ${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo

if ! command -v docker >/dev/null 2>&1; then
  echo -e "${RED}✗ Docker is not installed.${NC}"
  echo
  echo "  Please install Docker Desktop from:"
  echo "    https://www.docker.com/products/docker-desktop/"
  echo
  echo "  Then re-run this script."
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo -e "${RED}✗ Docker is installed but not running.${NC}"
  echo "  Please open Docker Desktop and wait for it to start, then re-run."
  exit 1
fi
echo -e "${GREEN}✓${NC} Docker is installed and running"

if ! docker compose version >/dev/null 2>&1; then
  echo -e "${RED}✗ Docker Compose v2 is required (your Docker is too old).${NC}"
  echo "  Please update Docker Desktop to the latest version."
  exit 1
fi
echo -e "${GREEN}✓${NC} Docker Compose is available"

if [ -f .env ]; then
  echo
  echo -e "${YELLOW}⚠  A .env file already exists.${NC}"
  read -p "  Overwrite it with a fresh configuration? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "  Keeping existing .env. Skipping wizard."
    SKIP_ENV=1
  fi
fi

if [ -z "${SKIP_ENV:-}" ]; then
  echo
  echo -e "${CYAN}━━━ Configuration ━━━${NC}"
  echo

  while true; do
    read -p "  Owner email (e.g. you@yourbusiness.com): " OWNER_EMAIL
    if [[ "$OWNER_EMAIL" =~ ^[^@]+@[^@]+\.[^@]+$ ]]; then break; fi
    echo -e "  ${RED}Please enter a valid email address.${NC}"
  done

  while true; do
    read -s -p "  Owner password (min 8 characters): " OWNER_PASSWORD
    echo
    if [ ${#OWNER_PASSWORD} -lt 8 ]; then
      echo -e "  ${RED}Password must be at least 8 characters.${NC}"
      continue
    fi
    read -s -p "  Confirm password: " OWNER_PASSWORD_CONFIRM
    echo
    if [ "$OWNER_PASSWORD" != "$OWNER_PASSWORD_CONFIRM" ]; then
      echo -e "  ${RED}Passwords do not match. Try again.${NC}"
      continue
    fi
    break
  done

  echo
  echo "  Application URL — the address users type into their browser."
  echo "    Just this machine:  http://localhost:3000"
  echo "    Tailscale network:  http://YOUR-TAILSCALE-NAME:3000"
  read -p "  Application URL [http://localhost:3000]: " NEXTAUTH_URL
  NEXTAUTH_URL="${NEXTAUTH_URL:-http://localhost:3000}"

  echo
  echo -e "${CYAN}━━━ Generating secrets ━━━${NC}"

  if command -v openssl >/dev/null 2>&1; then
    DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)
    NEXTAUTH_SECRET=$(openssl rand -base64 32)
  else
    DB_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 24)
    NEXTAUTH_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9+/' < /dev/urandom | head -c 44)
  fi
  echo -e "${GREEN}✓${NC} Database password generated"
  echo -e "${GREEN}✓${NC} Session secret generated"

  cat > .env <<EOF
# Generated by CHPMS setup wizard on $(date)
# DO NOT commit this file or share these values.

DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL="postgresql://chpms_user:${DB_PASSWORD}@db:5432/chpms"
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=${NEXTAUTH_URL}
OWNER_EMAIL=${OWNER_EMAIL}
OWNER_PASSWORD=${OWNER_PASSWORD}
SYSTEM_MODE=live
BACKUP_RETENTION_DAYS=7
BACKUP_RETENTION_WEEKS=4
APP_BIND_IP=0.0.0.0
EOF

  chmod 600 .env
  echo -e "${GREEN}✓${NC} .env created and secured"
fi

echo
echo -e "${CYAN}━━━ Loading application image ━━━${NC}"

if docker image inspect chpms:1.0.0 >/dev/null 2>&1; then
  echo -e "${GREEN}✓${NC} chpms:1.0.0 already loaded — skipping"
else
  if [ ! -f chpms-1.0.0.tar.gz ]; then
    echo -e "${RED}✗ chpms-1.0.0.tar.gz not found in current folder.${NC}"
    echo "  Make sure you ran this script from inside the unzipped delivery folder."
    exit 1
  fi
  echo "  Loading chpms-1.0.0.tar.gz (this can take 1–2 minutes)..."
  gunzip -c chpms-1.0.0.tar.gz | docker load
  echo -e "${GREEN}✓${NC} Application image loaded"
fi

echo
echo -e "${CYAN}━━━ Pulling supporting images (PostgreSQL) ━━━${NC}"
echo "  This needs internet on first run. Subsequent starts are offline."
docker compose pull db backup 2>&1 | grep -E "Pulled|Pulling|exists" || true

echo
echo -e "${CYAN}━━━ Starting CHPMS ━━━${NC}"
docker compose up -d

echo
echo -n "  Waiting for the application to become ready"
for i in $(seq 1 60); do
  if curl -s -f http://localhost:3000/api/health >/dev/null 2>&1; then
    echo
    echo -e "${GREEN}✓${NC} Application is ready"
    break
  fi
  echo -n "."
  sleep 2
done

echo
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Installation complete!${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo
echo "  Open in your browser:    $(grep '^NEXTAUTH_URL=' .env | cut -d'=' -f2)"
echo "  Owner email:             $(grep '^OWNER_EMAIL=' .env | cut -d'=' -f2)"
echo "  Owner password:          (the password you just set)"
echo
echo "  Common commands:"
echo "    docker compose stop          — stop the system (data preserved)"
echo "    docker compose start         — start it back up"
echo "    docker compose logs -f app   — watch application logs"
echo
echo "  Read README.md for backup, updates, and troubleshooting."
echo

if command -v open >/dev/null 2>&1; then
  open "$(grep '^NEXTAUTH_URL=' .env | cut -d'=' -f2)" 2>/dev/null || true
fi
