@echo off
REM CHPMS — Interactive Setup Wizard (Windows)
REM Double-click this file or run from a Command Prompt inside the unzipped
REM delivery folder.

setlocal EnableDelayedExpansion
cd /d "%~dp0"

echo.
echo ============================================================
echo   CHPMS - Coconut Husk Processing Management System
echo   Setup Wizard v1.0
echo ============================================================
echo.

where docker >nul 2>&1
if errorlevel 1 (
  echo [X] Docker is not installed.
  echo.
  echo     Please install Docker Desktop from:
  echo       https://www.docker.com/products/docker-desktop/
  echo.
  echo     Then re-run this script.
  pause
  exit /b 1
)
echo [OK] Docker is installed

docker info >nul 2>&1
if errorlevel 1 (
  echo [X] Docker is installed but not running.
  echo     Please open Docker Desktop and wait for it to start, then re-run.
  pause
  exit /b 1
)
echo [OK] Docker is running

if exist .env (
  echo.
  set /p OVERWRITE="A .env file already exists. Overwrite? (y/N) "
  if /i not "!OVERWRITE!"=="y" (
    echo Keeping existing .env. Skipping wizard.
    goto LOAD_IMAGE
  )
)

echo.
echo --- Configuration ---
echo.

:GET_EMAIL
set /p OWNER_EMAIL="  Owner email (e.g. you@yourbusiness.com): "
echo !OWNER_EMAIL! | findstr /r "^[^@][^@]*@[^@][^@]*\.[^@][^@]*$" >nul
if errorlevel 1 (
  echo   Please enter a valid email address.
  goto GET_EMAIL
)

:GET_PASSWORD
set /p OWNER_PASSWORD="  Owner password (min 8 characters): "
set "PWLEN=0"
set "TMP=!OWNER_PASSWORD!"
:COUNT_LOOP
if defined TMP (
  set "TMP=!TMP:~1!"
  set /a PWLEN+=1
  goto COUNT_LOOP
)
if !PWLEN! lss 8 (
  echo   Password must be at least 8 characters.
  goto GET_PASSWORD
)
set /p OWNER_PASSWORD_CONFIRM="  Confirm password: "
if not "!OWNER_PASSWORD!"=="!OWNER_PASSWORD_CONFIRM!" (
  echo   Passwords do not match. Try again.
  goto GET_PASSWORD
)

echo.
echo   Application URL - the address users type into their browser.
echo     Just this machine:  http://localhost:3000
echo     Tailscale network:  http://YOUR-TAILSCALE-NAME:3000
set /p NEXTAUTH_URL="  Application URL [http://localhost:3000]: "
if "!NEXTAUTH_URL!"=="" set "NEXTAUTH_URL=http://localhost:3000"

echo.
echo --- Generating secrets ---
for /f "delims=" %%i in ('powershell -NoProfile -Command "[Convert]::ToBase64String((1..18 ^| %%{Get-Random -Maximum 256})) -replace '[/+=]','' -replace '^(.{24}).*','$1'"') do set "DB_PASSWORD=%%i"
for /f "delims=" %%i in ('powershell -NoProfile -Command "[Convert]::ToBase64String((1..32 ^| %%{Get-Random -Maximum 256}))"') do set "NEXTAUTH_SECRET=%%i"
echo [OK] Database password generated
echo [OK] Session secret generated

(
  echo # Generated by CHPMS setup wizard
  echo # DO NOT commit this file or share these values.
  echo DB_PASSWORD=!DB_PASSWORD!
  echo DATABASE_URL="postgresql://chpms_user:!DB_PASSWORD!@db:5432/chpms"
  echo NEXTAUTH_SECRET=!NEXTAUTH_SECRET!
  echo NEXTAUTH_URL=!NEXTAUTH_URL!
  echo OWNER_EMAIL=!OWNER_EMAIL!
  echo OWNER_PASSWORD=!OWNER_PASSWORD!
  echo SYSTEM_MODE=live
  echo BACKUP_RETENTION_DAYS=7
  echo BACKUP_RETENTION_WEEKS=4
  echo APP_BIND_IP=0.0.0.0
) > .env
echo [OK] .env created

:LOAD_IMAGE
echo.
echo --- Loading application image ---
docker image inspect chpms:1.0.0 >nul 2>&1
if not errorlevel 1 (
  echo [OK] chpms:1.0.0 already loaded - skipping
  goto PULL_IMAGES
)
if not exist chpms-1.0.0.tar.gz (
  echo [X] chpms-1.0.0.tar.gz not found in current folder.
  pause
  exit /b 1
)
echo   Loading chpms-1.0.0.tar.gz (this can take 1-2 minutes)...
powershell -NoProfile -Command "& { $in = [System.IO.File]::OpenRead('chpms-1.0.0.tar.gz'); $gz = New-Object System.IO.Compression.GZipStream($in, [System.IO.Compression.CompressionMode]::Decompress); $out = [System.Diagnostics.Process]::Start([System.Diagnostics.ProcessStartInfo]@{ FileName='docker'; Arguments='load'; UseShellExecute=$false; RedirectStandardInput=$true }); $gz.CopyTo($out.StandardInput.BaseStream); $out.StandardInput.Close(); $out.WaitForExit() }"
echo [OK] Application image loaded

:PULL_IMAGES
echo.
echo --- Pulling supporting images (PostgreSQL) ---
docker compose pull db backup

echo.
echo --- Starting CHPMS ---
docker compose up -d

echo.
echo Waiting for the application to become ready...
for /l %%i in (1,1,60) do (
  curl -s -f http://localhost:3000/api/health >nul 2>&1
  if not errorlevel 1 goto READY
  timeout /t 2 /nobreak >nul
)
echo.
echo Taking longer than expected. Check `docker compose logs app` for details.
goto END

:READY
echo [OK] Application is ready

:END
echo.
echo ============================================================
echo   Installation complete!
echo ============================================================
echo.
for /f "tokens=2 delims==" %%a in ('findstr /b "NEXTAUTH_URL=" .env') do set "URL=%%a"
for /f "tokens=2 delims==" %%a in ('findstr /b "OWNER_EMAIL=" .env') do set "EMAIL=%%a"
echo   Open in your browser:    !URL!
echo   Owner email:             !EMAIL!
echo   Owner password:          (the password you just set)
echo.
echo   Common commands:
echo     docker compose stop          - stop the system (data preserved)
echo     docker compose start         - start it back up
echo     docker compose logs -f app   - watch application logs
echo.
echo   Read README.md for backup, updates, and troubleshooting.
echo.

start "" "!URL!"
pause
